---
# vars file for apache-perun
apache_package:
  Debian:
    - apache2
    - cronolog
  RedHat:
    - httpd
    - cronolog

apache_modules:
  - headers
  - ssl
  - proxy
  - proxy_ajp
  - proxy_http
  - rewrite
  - shib2

apache_service:
  Debian: apache2
  RedHat: httpd

ssl_cert_package:
  Debian: ssl-cert
  RedHat: crypto-utils

maintenance_files:
  - 401.html
  - 403.html
  - 404.html
  - 500.html
  - 503.html
  - certneeded.html
  - error.html
  - igtf-certneeded.html
  - maintenance.html
