---
- name: Require RHEL or CentOS 7
  assert:
    that:
      - ansible_distribution == "CentOS" or ansible_distribution == "RedHat Enterprise Linux"
      - ansible_distribution_major_version == "7"
    msg: "RHEL specific tasks"

- name: fix cmd prompt
  blockinfile:
    dest: /root/.bashrc
    block: |
     # If this is an xterm set the title to user@host:dir
     case "$TERM" in
     xterm*|rxvt*)
        PS1="\[\e]0;\u@$(hostname --fqdn) \w\a\]\u@$(hostname --fqdn):\w# "
        ;;
     *)
        ;;
     esac

- name: Use cronolog for error log rotation
  lineinfile:
    path: "/etc/httpd/conf/httpd.conf"
    regexp: 'ErrorLog logs/error.log'
    line: 'ErrorLog "|/sbin/cronolog /var/log/httpd/%Y/%m/%d/error.log"'
    backrefs: yes
  notify:
      - "restart webserver"

- name: Use cronolog for access log rotation
  lineinfile:
    path: "/etc/httpd/conf/httpd.conf"
    regexp: 'CustomLog "logs/access_log" combined'
    line: 'CustomLog "|/sbin/cronolog /var/log/httpd/%Y/%m/%d/access.log" vhost_combined'
    backrefs: yes
  notify:
      - "restart webserver"

- name: Set up TLS correctly
  blockinfile:
    dest: "/etc/httpd/conf.modules.d/00-ssl.conf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: 'LoadModule ssl_module modules/mod_ssl.so'
    block: |
      # see https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=apache-2.4.25&openssl=1.0.2l&hsts=yes&profile=modern
      SSLProtocol             all -SSLv3 -TLSv1 -TLSv1.1
      SSLCipherSuite          ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
      SSLHonorCipherOrder     on
      SSLCompression          off

      # OCSP Stapling, only in httpd 2.3.3 and later
      SSLUseStapling          on
      SSLStaplingResponderTimeout 5
      SSLStaplingReturnResponderErrors off
      SSLStaplingCache        shmcb:/var/run/ocsp(128000)
  notify:
      - "restart webserver"
