---
- include_tasks: "{{ ansible_os_family }}.yml"

- include_tasks: "certificates.yml"
  when: apache_certificate_file == "/etc/perun/ssl/perun.pem"

- include_tasks: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"

- name: Restart server if needed
  meta: flush_handlers
